### ISSUE TITLE
Leyla ile Mecnun was one of the best tv series in Turkey

### ISSUE THREAD

**Issue by KebSegir** [TheCabbar/super-git-repo#4]
You should add more things related to Leyla ile Mecnun

**Comment by amantenqrim** [comment]
Leyla ile Mecnun yazabilirsin gibi bir cevap verılebılır mı burada ?

**Comment by KebSegir** [comment]
I think we can consider something more about Leyla ile Mecnun!

2af1d85fcafb6b6caaf5057654d5b1c37232f379
